"""Plan and write a new workload into a checkout of this repository (S039, T-81).

``plan_workload`` reads the tree and returns what would be written; it writes
nothing. ``write_plan`` writes it. Every edit of an existing file is made as
text, after the last line of its table or list (a YAML or TOML writer would drop
the file's comments), and is verified before the plan is returned: the new
``pyproject.toml`` must parse to the old one plus exactly two entry points, and
a copy of the registry with the new ``agents.yaml`` must validate.

The command declares and never grants: the agent lists no tool and no tenant
lists it, so the gateway refuses its model calls and no tool server answers it
until a person adds both in a reviewed change (T-81).

The templates are text files filled with ``string.Template``: a ``.py`` file
under ``meridian.platform`` that imports LangGraph would break the import
contract (hard rule 5). Only ``$name`` and ``$module`` are substituted. Every
refusal is a fixed text that never quotes the name.
"""

import copy
import hashlib
import json
import keyword
import os
import re
import shutil
import stat
import string
import tempfile
import tomllib
from collections.abc import Mapping
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from types import MappingProxyType
from typing import Any

import yaml

from meridian.platform.registry.loader import RegistryError, load_registry

MAX_NAME_CHARS = 40
# The registry's agent ID, with a length limit. Used with fullmatch: an end
# anchor would accept a trailing newline.
NAME = re.compile(r"[a-z][a-z0-9]*(-[a-z0-9]+)*")

# Fixed texts: none quotes the name, which is the caller's own and may hold
# anything. The two that name an exception name its type only.
BAD_NAME = (
    f"the name must be at most {MAX_NAME_CHARS} characters: lower-case letters and "
    "digits, starting with a letter, groups joined by single hyphens, and a "
    "Python identifier that is no keyword once hyphens become underscores"
)
NOT_A_CHECKOUT = "the directory is not a checkout of the meridian repository"
REGISTRY_INVALID = (
    "the registry does not validate: run `meridian registry validate` and fix it first"
)
AMBIGUOUS_NAME = "the name is a word YAML reads as something other than text"
NAME_TAKEN = (
    "the name is taken: an agent, an entry point or a workload directory has it"
)
AGENTS_EDIT_UNVERIFIED = "the edit of agents.yaml does not verify; nothing was written"
PYPROJECT_EDIT_UNVERIFIED = (
    "the edit of pyproject.toml does not verify; nothing was written"
)
PATH_EXISTS = "a file or directory the workload would create already exists"
WRITE_FAILED = "writing the workload failed ({}); what was written has been removed"
ROLLBACK_FAILED = (
    "writing the workload failed ({}) and could not be fully undone: "
    "check the working tree"
)

AGENTS_PATH = "config/registry/agents.yaml"
PYPROJECT_PATH = "pyproject.toml"
REGISTRY_DIRECTORY = "config/registry"
GRAPHS_GROUP = "meridian.graphs"
EVALUATIONS_GROUP = "meridian.evaluations"
TEMPLATES = ("templates", "workload")
# Template file -> where its rendering goes; {module} and {name} are filled in.
RENDERED_FILES = {
    "__init__.py.tmpl": "src/meridian/workloads/{module}/__init__.py",
    "graph.py.tmpl": "src/meridian/workloads/{module}/graph.py",
    "evaluation.py.tmpl": "src/meridian/workloads/{module}/evaluation.py",
    "test_scaffold.py.tmpl": (
        "tests/meridian/workloads/{module}/test_{module}_scaffold.py"
    ),
}
GOLDEN_DIRECTORY = "data/evaluation/{name}/golden"
CASES = "[]\n"
AGENT_DESCRIPTION = (
    "The {name} workload, generated by `meridian workload new`; it calls no tool."
)
# Lines that split a text into lines without dropping or changing a byte; unlike
# str.splitlines, only a line feed ends a line.
LINES = re.compile(r"[^\n]*\n|[^\n]+")


class ScaffoldError(Exception):
    """Refused or failed; the message is a fixed text and never quotes the name."""


@dataclass(frozen=True, slots=True)
class Plan:
    name: str  # the agent ID and the entry points' name
    module: str  # name with "-" replaced by "_"
    created: Mapping[str, str]  # relative POSIX path -> text of a new file
    changed: Mapping[str, str]  # relative POSIX path -> whole new text


def _module_of(name: str) -> str:
    """The module name for ``name``; refuse a name that is not safe to put in a
    path, a YAML value or a TOML key, or that YAML would not read as text."""
    if (
        not isinstance(name, str)
        or len(name) > MAX_NAME_CHARS
        or NAME.fullmatch(name) is None
    ):
        raise ScaffoldError(BAD_NAME)
    module = name.replace("-", "_")
    if not module.isidentifier() or keyword.iskeyword(module):
        raise ScaffoldError(BAD_NAME)
    # Such an ID (yes, no, on, off, true, false, null) would also be read as a
    # boolean or null wherever a person lists the agent later, for example in a
    # tenant's ``agents: [...]``. Derived from the parser, not from a word list.
    if yaml.safe_load(name) != name:
        raise ScaffoldError(AMBIGUOUS_NAME)
    return module


def _read_pyproject(root: Path) -> tuple[str, dict[str, Any]]:
    """The text of ``pyproject.toml`` and what it parses to, for a checkout of
    this repository; raise ``ScaffoldError`` for any other tree."""
    try:
        text = (root / PYPROJECT_PATH).read_bytes().decode("utf-8")
        document = tomllib.loads(text)
    except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError):
        raise ScaffoldError(NOT_A_CHECKOUT) from None
    project = document.get("project")
    if not isinstance(project, dict) or project.get("name") != "meridian":
        raise ScaffoldError(NOT_A_CHECKOUT)
    entry_points = project.get("entry-points")
    if not isinstance(entry_points, dict) or not all(
        isinstance(entry_points.get(group), dict)
        for group in (GRAPHS_GROUP, EVALUATIONS_GROUP)
    ):
        raise ScaffoldError(NOT_A_CHECKOUT)
    if not (root / AGENTS_PATH).is_file():
        raise ScaffoldError(NOT_A_CHECKOUT)
    if not (root / "src" / "meridian" / "workloads").is_dir():
        raise ScaffoldError(NOT_A_CHECKOUT)
    return text, document


def _taken_paths(name: str, module: str) -> tuple[str, ...]:
    return (
        f"src/meridian/workloads/{module}",
        f"tests/meridian/workloads/{module}",
        f"data/evaluation/{name}",
    )


def _refuse_a_taken_name(
    root: Path, name: str, module: str, document: Mapping[str, Any], agent_exists: bool
) -> None:
    entry_points = document["project"]["entry-points"]
    published = any(name in entry_points[g] for g in (GRAPHS_GROUP, EVALUATIONS_GROUP))
    occupied = any(
        os.path.lexists(root / relative) for relative in _taken_paths(name, module)
    )
    if agent_exists or published or occupied:
        raise ScaffoldError(NAME_TAKEN)


def _template(file: str) -> string.Template:
    directory = resources.files("meridian.platform.cli").joinpath(*TEMPLATES)
    return string.Template(directory.joinpath(file).read_text(encoding="utf-8"))


def _created_files(name: str, module: str) -> dict[str, str]:
    created = {
        RENDERED_FILES[file].format(module=module): _template(file).substitute(
            name=name, module=module
        )
        for file in RENDERED_FILES
    }
    golden = GOLDEN_DIRECTORY.format(name=name)
    digest = hashlib.sha256(CASES.encode("utf-8")).hexdigest()
    manifest = {
        "synthetic": True,
        "generator_version": "0",
        "seed": 0,
        "files": {"cases.json": digest},
    }
    created[f"{golden}/cases.json"] = CASES
    created[f"{golden}/manifest.json"] = json.dumps(manifest, indent=2) + "\n"
    return created


def _agents_edit(root: Path, name: str) -> str:
    """The text of ``agents.yaml`` with the new agent appended, verified."""
    path = root / AGENTS_PATH
    try:
        old = path.read_bytes().decode("utf-8")
    except (OSError, UnicodeDecodeError):
        raise ScaffoldError(NOT_A_CHECKOUT) from None
    description = AGENT_DESCRIPTION.format(name=name)
    block = f"  - id: {name}\n    description: {description}\n    tools: []\n"
    new = old + ("" if old.endswith("\n") else "\n") + block
    agent = {"id": name, "description": description, "tools": []}
    try:
        before = yaml.safe_load(old)
        expected = {**before, "agents": [*before["agents"], agent]}
        if yaml.safe_load(new) != expected:
            raise ScaffoldError(AGENTS_EDIT_UNVERIFIED)
        _registry_with(root / REGISTRY_DIRECTORY, new)
    except (yaml.YAMLError, TypeError, KeyError, RegistryError, OSError):
        raise ScaffoldError(AGENTS_EDIT_UNVERIFIED) from None
    return new


def _registry_with(registry_directory: Path, agents_text: str) -> None:
    """Validate a copy of the registry whose ``agents.yaml`` is ``agents_text``."""
    with tempfile.TemporaryDirectory() as temporary:
        copy = Path(temporary) / "registry"
        shutil.copytree(registry_directory, copy)
        (copy / "agents.yaml").write_bytes(agents_text.encode("utf-8"))
        load_registry(copy)


def _with_entry_point(text: str, group: str, line: str) -> str:
    """``text`` with ``line`` after the last key line of the table of ``group``;
    the table ends at the next line that starts with ``[`` or at the end of the
    file, and the blank and comment lines after its last key stay after ``line``.
    Raise ``ScaffoldError`` when the table's header line is not found."""
    lines = LINES.findall(text)
    header = f'[project.entry-points."{group}"]'
    starts = [i for i, each in enumerate(lines) if each.strip() == header]
    if len(starts) != 1:
        raise ScaffoldError(PYPROJECT_EDIT_UNVERIFIED)
    last = starts[0]
    for index in range(starts[0] + 1, len(lines)):
        if lines[index].startswith("["):
            break
        if lines[index].strip() and not lines[index].lstrip().startswith("#"):
            last = index
    if lines[last].endswith("\n"):
        ending = "\r\n" if lines[last].endswith("\r\n") else "\n"
        lines.insert(last + 1, line + ending)
    else:
        # The last line of a file with no final newline: it gets the file's line
        # ending, and the inserted line, now last, has none.
        lines[last] += "\r\n" if "\r\n" in text else "\n"
        lines.append(line)
    return "".join(lines)


def _pyproject_edit(
    old: str, document: Mapping[str, Any], name: str, module: str
) -> str:
    """The text of ``pyproject.toml`` with the two entry points, verified."""
    values = {
        GRAPHS_GROUP: f"meridian.workloads.{module}.graph:build",
        EVALUATIONS_GROUP: f"meridian.workloads.{module}.evaluation:EVALUATION",
    }
    new = old
    for group, value in values.items():
        new = _with_entry_point(new, group, f'{name} = "{value}"')
    expected = copy.deepcopy(document)
    for group, value in values.items():
        expected["project"]["entry-points"][group][name] = value
    try:
        verified = tomllib.loads(new) == expected
    except tomllib.TOMLDecodeError:
        verified = False
    if not verified:
        raise ScaffoldError(PYPROJECT_EDIT_UNVERIFIED)
    return new


def plan_workload(root: Path, name: str) -> Plan:
    """What ``meridian workload new NAME`` would write under ``root``. Reads
    only. Refuse, in this order: a bad name, a tree that is not a checkout of
    this repository, a registry that does not validate, a name that is taken and
    an edit that does not verify."""
    module = _module_of(name)
    pyproject, document = _read_pyproject(root)
    try:
        registry = load_registry(root / REGISTRY_DIRECTORY)
    except RegistryError:
        raise ScaffoldError(REGISTRY_INVALID) from None
    _refuse_a_taken_name(root, name, module, document, registry.agent(name) is not None)
    created = _created_files(name, module)
    changed = {
        AGENTS_PATH: _agents_edit(root, name),
        PYPROJECT_PATH: _pyproject_edit(pyproject, document, name, module),
    }
    return Plan(
        name=name,
        module=module,
        created=MappingProxyType(created),
        changed=MappingProxyType(changed),
    )


def _replace(path: Path, data: bytes) -> None:
    """Replace ``path`` with ``data`` in one step, keeping its mode: the bytes go
    to a temporary file beside it, which then takes its place."""
    mode = stat.S_IMODE(path.stat().st_mode)
    descriptor, temporary = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
    )
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise


def _make_directories(directory: Path, made: list[Path]) -> None:
    """Create ``directory`` and the parents that are missing, noting each one
    this call made in ``made``, outermost first."""
    missing = []
    current = directory
    while not os.path.lexists(current):
        missing.append(current)
        current = current.parent
    for each in reversed(missing):
        each.mkdir()
        made.append(each)


def _undo(
    files: list[Path], directories: list[Path], restore: Path | None, old: bytes
) -> bool:
    """Put back what a failed write changed; whether everything went back."""
    clean = True
    if restore is not None:
        try:
            _replace(restore, old)
        except OSError:
            clean = False
    for file in files:
        try:
            file.unlink(missing_ok=True)
        except OSError:
            clean = False
    for directory in reversed(directories):
        try:
            directory.rmdir()
        except OSError:
            clean = False
    return clean


def write_plan(root: Path, plan: Plan) -> None:
    """Write ``plan`` under ``root``: the new files, then ``agents.yaml``, then
    ``pyproject.toml``, whose entry points are what makes the platform load the
    workload. When a write fails, remove what this call made, put ``agents.yaml``
    back and raise ``ScaffoldError``."""
    targets = [(root / relative, text) for relative, text in plan.created.items()]
    if any(os.path.lexists(path) for path, _ in targets):
        raise ScaffoldError(PATH_EXISTS)
    files: list[Path] = []
    directories: list[Path] = []
    agents = root / AGENTS_PATH
    old_agents = b""
    replaced: Path | None = None
    try:
        for path, text in targets:
            _make_directories(path.parent, directories)
            with open(path, "x", encoding="utf-8", newline="\n") as stream:
                files.append(path)
                stream.write(text)
        old_agents = agents.read_bytes()
        _replace(agents, plan.changed[AGENTS_PATH].encode("utf-8"))
        replaced = agents
        _replace(root / PYPROJECT_PATH, plan.changed[PYPROJECT_PATH].encode("utf-8"))
    except OSError as exc:
        undone = _undo(files, directories, replaced, old_agents)
        message = WRITE_FAILED if undone else ROLLBACK_FAILED
        raise ScaffoldError(message.format(type(exc).__name__)) from None
