#!/usr/bin/env bash
# Bootstrap the Terraform remote state: `make azure-state`. Safe to run again; it
# converges. Creates Azure resources (a few cents a month), so the owner runs it.
#   0. the resource providers Terraform and the state need are registered
#   1. resource group rg-meridian-tfstate in Sweden Central
#   2. storage account stmeridiantf<suffix>: ZRS, TLS 1.2, HTTPS only, no public
#      blobs, shared keys off (Entra ID only)
#   3. blob versioning and 14-day soft delete for blobs and containers
#   4. Storage Blob Data Contributor for the signed-in user, at the account
#   5. container tfstate
#   6. a CanNotDelete lock on the resource group
#   7. infra/terraform/local.env (gitignored): the subscription pin and the
#      account name that foundation.sh hands to Terraform's backend
# The subscription is AZURE_SUBSCRIPTION (name or ID), required on the first run;
# the az default account is never used. Once local.env exists it is the pin and
# a different subscription stops the script.
set -euo pipefail

# shellcheck source=common.sh
. "$(dirname "${BASH_SOURCE[0]}")/common.sh"

readonly STATE_DATA_ROLE="Storage Blob Data Contributor"
readonly LOCK_NAME=lock-tfstate
readonly SOFT_DELETE_DAYS=14
readonly ROLE_WAIT_SECONDS=300
readonly ROLE_RETRY_INTERVAL=15
# Terraform cannot rebuild lost state; the tags say what the account is for.
readonly STATE_TAGS=(project=meridian managed-by=script purpose=terraform-state)

# match_subscription WANTED SOURCE: print the {id,name,state} of the one
# subscription that WANTED names; SOURCE says where WANTED came from, for the
# error messages. `az account show --subscription <name>` silently picks one of
# several subscriptions with the same name (every new account starts as
# "Azure subscription 1"), so the list is searched here instead: an exact ID
# wins, otherwise the name must match exactly one. No ID is printed on failure.
match_subscription() {
  local wanted=$1 source=$2 all matches count
  all="$(az account list --all --query '[].{id:id,name:name,state:state}' -o json 2>/dev/null)" ||
    die "az cannot list subscriptions; run 'az login'"
  matches="$(jq -c --arg wanted "${wanted}" \
    '[.[] | select((.id | ascii_downcase) == ($wanted | ascii_downcase))]' <<<"${all}")"
  if [[ "$(jq length <<<"${matches}")" == 0 ]]; then
    matches="$(jq -c --arg wanted "${wanted}" '[.[] | select(.name == $wanted)]' <<<"${all}")"
  fi
  count="$(jq length <<<"${matches}")"
  case "${count}" in
    0) die "${source} matches no subscription that az can see; run 'az login' or check the value" ;;
    1) jq -c '.[0]' <<<"${matches}" ;;
    *) die "${source} matches ${count} subscriptions named '${wanted}'; rename one (Azure portal, Subscriptions) or pass the subscription ID" ;;
  esac
}

# Resolve the subscription to bootstrap: sets ARM_SUBSCRIPTION_ID and
# subscription_name, and exports ARM_TENANT_ID. The az default account is never
# used. The first run needs AZURE_SUBSCRIPTION (name or ID). Once local.env
# exists it is the pin: without AZURE_SUBSCRIPTION the pinned subscription is
# used, and with one that names another subscription the script stops.
resolve_subscription() {
  local pinned="" info
  if [[ -f "${LOCAL_ENV}" ]]; then
    # A subshell, so sourcing local.env cannot change this script's variables.
    # shellcheck disable=SC1090 # LOCAL_ENV is generated by this script
    pinned="$(
      unset ARM_SUBSCRIPTION_ID
      . "${LOCAL_ENV}" 2>/dev/null
      printf '%s' "${ARM_SUBSCRIPTION_ID:-}"
    )"
    [[ -n "${pinned}" ]] || die "${LOCAL_ENV} has no ARM_SUBSCRIPTION_ID; remove it deliberately and rerun"
  fi

  if [[ -n "${AZURE_SUBSCRIPTION:-}" ]]; then
    info="$(match_subscription "${AZURE_SUBSCRIPTION}" AZURE_SUBSCRIPTION)"
  elif [[ -n "${pinned}" ]]; then
    info="$(match_subscription "${pinned}" "the subscription pinned in local.env")"
  else
    die "AZURE_SUBSCRIPTION is not set. Choose the subscription by name or ID, e.g. AZURE_SUBSCRIPTION=\"<subscription name>\" make azure-state"
  fi
  ARM_SUBSCRIPTION_ID="$(jq -r .id <<<"${info}")"
  subscription_name="$(jq -r .name <<<"${info}")"
  [[ "$(jq -r .state <<<"${info}")" == Enabled ]] ||
    die "subscription '${subscription_name}' is not Enabled"
  export ARM_SUBSCRIPTION_ID

  if [[ -n "${pinned}" && "${pinned}" != "${ARM_SUBSCRIPTION_ID}" ]]; then
    die "${LOCAL_ENV} pins another subscription than '${subscription_name}'. Set AZURE_SUBSCRIPTION to the pinned one, or remove local.env deliberately to start over."
  fi
  pin_tenant
  log "subscription: ${subscription_name}"
}

# Register the resource providers the state storage and the foundation module
# use. A new subscription has most of them unregistered, and the module's
# provider is set not to register any (providers.tf), so its plan changes
# nothing in Azure.
ensure_providers() {
  local namespace state
  for namespace in Microsoft.Storage Microsoft.KeyVault Microsoft.CognitiveServices \
    Microsoft.Insights Microsoft.Consumption; do
    state="$(azc provider show --namespace "${namespace}" --query registrationState -o tsv)"
    if [[ "${state}" == Registered ]]; then
      log "provider ${namespace} is registered"
      continue
    fi
    log "registering provider ${namespace} (${state}); this can take a minute"
    azc provider register --namespace "${namespace}" --wait >/dev/null
  done
}

ensure_resource_group() {
  if [[ "$(azc group exists --name "${STATE_RESOURCE_GROUP}")" == true ]]; then
    log "resource group ${STATE_RESOURCE_GROUP} exists"
    return
  fi
  log "creating resource group ${STATE_RESOURCE_GROUP} in ${STATE_LOCATION}"
  azc group create --name "${STATE_RESOURCE_GROUP}" --location "${STATE_LOCATION}" \
    --tags "${STATE_TAGS[@]}" >/dev/null
}

# Print the account's resource ID, or nothing when it does not exist. A list,
# not `show`, so that "not found" is not confused with an authorisation error.
storage_account_id() {
  azc storage account list --resource-group "${STATE_RESOURCE_GROUP}" \
    --query "[?name=='$1'].id | [0]" -o tsv
}

# The security settings are applied on create and re-applied on every run, so a
# setting changed by hand is put back.
ensure_storage_account() {
  account="$(state_account_name "${ARM_SUBSCRIPTION_ID}")"
  if [[ -n "$(storage_account_id "${account}")" ]]; then
    log "storage account ${account} exists; re-applying its security settings"
    azc storage account update --name "${account}" --resource-group "${STATE_RESOURCE_GROUP}" \
      --min-tls-version TLS1_2 --https-only true --allow-blob-public-access false \
      --allow-shared-key-access false >/dev/null
  else
    log "creating storage account ${account} (Standard_ZRS, ${STATE_LOCATION})"
    azc storage account create --name "${account}" --resource-group "${STATE_RESOURCE_GROUP}" \
      --location "${STATE_LOCATION}" --sku Standard_ZRS --kind StorageV2 \
      --min-tls-version TLS1_2 --https-only true --allow-blob-public-access false \
      --allow-shared-key-access false --tags "${STATE_TAGS[@]}" >/dev/null
  fi
  account_id="$(storage_account_id "${account}")"
  [[ -n "${account_id}" ]] || die "storage account ${account} is not visible after it was created"

  # The az storage account commands have no flag for defaultToOAuthAuthentication,
  # so the PATCH they would send is sent by hand. It makes the portal and tools
  # that honour it default to Entra ID rather than an account key.
  azc rest --method patch \
    --url "https://management.azure.com${account_id}?api-version=2023-05-01" \
    --body '{"properties":{"defaultToOAuthAuthentication":true}}' >/dev/null
}

# Versioning keeps every earlier state file; soft delete keeps a removed blob or
# container for 14 days. Together they make a bad apply or an accidental removal
# recoverable.
ensure_blob_protection() {
  log "blob protection: versioning, ${SOFT_DELETE_DAYS}-day soft delete for blobs and containers"
  azc storage account blob-service-properties update \
    --account-name "${account}" --resource-group "${STATE_RESOURCE_GROUP}" \
    --enable-versioning true \
    --enable-delete-retention true --delete-retention-days "${SOFT_DELETE_DAYS}" \
    --enable-container-delete-retention true --container-delete-retention-days "${SOFT_DELETE_DAYS}" \
    >/dev/null
}

# Shared keys are off, so the signed-in user reads and writes state through this
# data-plane role. Owner or Contributor is a control-plane role and gives no
# access to blobs.
ensure_role() {
  local object_id existing
  object_id="$(signed_in_object_id)"
  # By object ID: resolving --assignee through Graph fails for guest accounts.
  existing="$(azc role assignment list --assignee-object-id "${object_id}" --role "${STATE_DATA_ROLE}" \
    --scope "${account_id}" --query 'length(@)' -o tsv)"
  if [[ "${existing}" != 0 ]]; then
    log "role ${STATE_DATA_ROLE} is assigned"
    return
  fi
  log "assigning ${STATE_DATA_ROLE} at the storage account"
  azc role assignment create --assignee-object-id "${object_id}" --assignee-principal-type User \
    --role "${STATE_DATA_ROLE}" --scope "${account_id}" >/dev/null
}

# A new role assignment takes a few minutes to reach the blob service. Only an
# authorisation failure is retried; any other error stops the script.
ensure_container() {
  local deadline=$((SECONDS + ROLE_WAIT_SECONDS)) out
  while :; do
    if out="$(azc storage container create --name "${STATE_CONTAINER}" \
      --account-name "${account}" --auth-mode login 2>&1)"; then
      log "container ${STATE_CONTAINER} exists"
      return
    fi
    if ! grep -qiE 'AuthorizationPermissionMismatch|AuthorizationFailure|not authorized|does not have authorization|required permissions needed|blocked by network rules|403' <<<"${out}"; then
      die "creating container ${STATE_CONTAINER} failed: ${out}"
    fi
    if ((SECONDS >= deadline)); then
      die "still no permission on ${account} after ${ROLE_WAIT_SECONDS}s: ${out}"
    fi
    log "waiting for the role assignment to propagate (up to ${ROLE_WAIT_SECONDS}s)"
    sleep "${ROLE_RETRY_INTERVAL}"
  done
}

ensure_lock() {
  local existing
  existing="$(azc lock list --resource-group "${STATE_RESOURCE_GROUP}" \
    --query "[?name=='${LOCK_NAME}'] | length(@)" -o tsv)"
  if [[ "${existing}" != 0 ]]; then
    log "lock ${LOCK_NAME} exists"
    return
  fi
  log "locking ${STATE_RESOURCE_GROUP} against removal (${LOCK_NAME})"
  azc lock create --name "${LOCK_NAME}" --lock-type CanNotDelete \
    --resource-group "${STATE_RESOURCE_GROUP}" \
    --notes "Terraform state for Meridian; remove deliberately" >/dev/null
}

# Written last, so its existence means the bootstrap completed. Atomic: a
# reader never sees half a file, and the mode is 600 before any content lands.
write_local_env() {
  local tmp
  tmp="$(mktemp "${LOCAL_ENV}.XXXXXX")"
  # shellcheck disable=SC2064 # expand ${tmp} now: it is the file to remove
  trap "rm -f '${tmp}'" EXIT
  chmod 600 "${tmp}"
  printf '# generated by state.sh; gitignored\nARM_SUBSCRIPTION_ID=%s\nTF_STATE_STORAGE_ACCOUNT=%s\n' \
    "${ARM_SUBSCRIPTION_ID}" "${account}" >"${tmp}"
  mv "${tmp}" "${LOCAL_ENV}"
  log "wrote ${LOCAL_ENV}"
}

need_tools az jq shasum
resolve_subscription
ensure_providers
ensure_resource_group
ensure_storage_account
ensure_blob_protection
ensure_role
ensure_container
ensure_lock
write_local_env

log "state is ready:"
printf '  resource group   %s (CanNotDelete lock %s)\n' "${STATE_RESOURCE_GROUP}" "${LOCK_NAME}"
printf '  storage account  %s (ZRS, Entra ID only, versioning, %s-day soft delete)\n' "${account}" "${SOFT_DELETE_DAYS}"
printf '  container        %s\n' "${STATE_CONTAINER}"
printf 'next: make azure-plan\n'
