"""The workload scaffold's planning and writing (S039, T-81).

Every test builds a small tree in ``tmp_path``: a copy of this repository's
``pyproject.toml`` and registry and an empty workloads directory. Nothing here
touches the real checkout.
"""

import hashlib
import json
import os
import stat
import subprocess
import sys
import tomllib
from collections.abc import Callable, Mapping
from pathlib import Path
from typing import Any

import pytest
import yaml

from meridian.platform.cli import scaffold
from meridian.platform.cli.scaffold import (
    AGENTS_EDIT_UNVERIFIED,
    AMBIGUOUS_NAME,
    BAD_NAME,
    MAX_NAME_CHARS,
    NAME_TAKEN,
    NOT_A_CHECKOUT,
    PATH_EXISTS,
    PYPROJECT_EDIT_UNVERIFIED,
    REGISTRY_INVALID,
    ROLLBACK_FAILED,
    WRITE_FAILED,
    Plan,
    ScaffoldError,
    plan_workload,
    write_plan,
)
from meridian.platform.evaluation.fingerprints import golden_set_of
from meridian.platform.registry.loader import load_registry

NAME = "fraud-review"
MODULE = "fraud_review"
GRAPHS = "meridian.graphs"
EVALUATIONS = "meridian.evaluations"
LONG_NAME = "a" * 20 + "-" + "b" * 19
RUFF_TIMEOUT_SECONDS = 60
# The small tree has no ``meridian.platform`` for ruff's import sorter to find, so
# it is told what the real checkout's layout shows it: ``meridian`` is ours.
FIRST_PARTY = ("--config", 'lint.isort.known-first-party = ["meridian"]')


def created_paths(module: str = MODULE, name: str = NAME) -> set[str]:
    return {
        f"src/meridian/workloads/{module}/__init__.py",
        f"src/meridian/workloads/{module}/graph.py",
        f"src/meridian/workloads/{module}/evaluation.py",
        f"tests/meridian/workloads/{module}/test_{module}_scaffold.py",
        f"data/evaluation/{name}/golden/cases.json",
        f"data/evaluation/{name}/golden/manifest.json",
    }


def snapshot(root: Path) -> dict[str, object]:
    """Every path under ``root``: a file's bytes, a symlink's target, a
    directory as ``None``, so that a stray directory or temp file shows."""
    found: dict[str, object] = {}
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root).as_posix()
        if path.is_symlink():
            found[relative] = ("link", os.readlink(path))
        elif path.is_dir():
            found[relative] = None
        else:
            found[relative] = path.read_bytes()
    return found


def edit(path: Path, change: Callable[[str], str]) -> None:
    text = path.read_bytes().decode("utf-8")
    path.write_bytes(change(text).encode("utf-8"))


def comment_lines(text: str) -> list[str]:
    return [line.strip() for line in text.splitlines() if line.lstrip()[:1] == "#"]


def test_a_plan_creates_six_files_and_changes_two_and_writes_nothing(
    root: Path,
) -> None:
    before = snapshot(root)

    plan = plan_workload(root, NAME)

    assert plan.name == NAME
    assert plan.module == MODULE
    assert set(plan.created) == created_paths()
    assert len(plan.created) == 6
    assert set(plan.changed) == {"config/registry/agents.yaml", "pyproject.toml"}
    assert snapshot(root) == before


def test_the_golden_set_text_is_an_empty_list_and_its_manifest(root: Path) -> None:
    plan = plan_workload(root, NAME)

    cases = plan.created[f"data/evaluation/{NAME}/golden/cases.json"]
    manifest = plan.created[f"data/evaluation/{NAME}/golden/manifest.json"]
    assert cases == "[]\n"
    digest = hashlib.sha256(cases.encode("utf-8")).hexdigest()
    assert manifest == (
        json.dumps(
            {
                "synthetic": True,
                "generator_version": "0",
                "seed": 0,
                "files": {"cases.json": digest},
            },
            indent=2,
        )
        + "\n"
    )


def test_the_new_agent_is_appended_to_agents_yaml_as_three_lines(root: Path) -> None:
    old = (root / "config/registry/agents.yaml").read_text(encoding="utf-8")

    plan = plan_workload(root, NAME)

    new = plan.changed["config/registry/agents.yaml"]
    assert new == (
        old
        + f"  - id: {NAME}\n"
        + f"    description: The {NAME} workload, generated by "
        + "`meridian workload new`; it calls no tool.\n"
        + "    tools: []\n"
    )


def test_a_file_without_a_final_newline_gets_one_before_the_agent(root: Path) -> None:
    path = root / "config/registry/agents.yaml"
    edit(path, str.rstrip)

    plan = plan_workload(root, NAME)

    new = plan.changed["config/registry/agents.yaml"]
    assert new.startswith(path.read_text(encoding="utf-8") + f"\n  - id: {NAME}\n")


def test_each_entry_point_follows_its_tables_last_key_line(root: Path) -> None:
    old = (root / "pyproject.toml").read_text(encoding="utf-8")

    plan = plan_workload(root, NAME)

    new = plan.changed["pyproject.toml"]
    graph_old = 'claims-triage = "meridian.workloads.claims_triage.graph:build"\n'
    graph_new = f'{NAME} = "meridian.workloads.{MODULE}.graph:build"\n'
    evaluation_old = (
        'claims-triage = "meridian.workloads.claims_triage.'
        'evaluation_http:EVALUATION"\n'
    )
    evaluation_new = f'{NAME} = "meridian.workloads.{MODULE}.evaluation:EVALUATION"\n'
    assert new == old.replace(graph_old, graph_old + graph_new).replace(
        evaluation_old, evaluation_old + evaluation_new
    )
    # The blank line and the comment that followed the graphs table stay after
    # the inserted key.
    assert graph_new + "\n# `meridian eval run`" in new


MINIMAL_PYPROJECT = (
    '[project]\nname = "meridian"\n\n'
    '[project.entry-points."meridian.graphs"]\nclaims-triage = "a.b:c"\n\n'
    "# a comment that belongs to the next table\n"
    '[project.entry-points."meridian.evaluations"]\nclaims-triage = "d.e:f"'
)


@pytest.mark.parametrize("line_ending", ["\n", "\r\n"], ids=["lf", "crlf"])
def test_the_line_endings_and_a_missing_final_newline_are_kept(
    root: Path, line_ending: str
) -> None:
    text = MINIMAL_PYPROJECT.replace("\n", line_ending)
    (root / "pyproject.toml").write_bytes(text.encode("utf-8"))
    graph_old = 'claims-triage = "a.b:c"'
    graph_new = f'{NAME} = "meridian.workloads.{MODULE}.graph:build"'
    evaluation_old = 'claims-triage = "d.e:f"'
    evaluation_new = f'{NAME} = "meridian.workloads.{MODULE}.evaluation:EVALUATION"'

    plan = plan_workload(root, NAME)

    # The inserted line takes the file's line ending, and the last line, which
    # had none, still has none.
    assert plan.changed["pyproject.toml"] == text.replace(
        graph_old, graph_old + line_ending + graph_new, 1
    ).replace(evaluation_old, evaluation_old + line_ending + evaluation_new, 1)


# Names the pattern, the length limit or the module check refuse.
BAD_NAMES = [
    "",
    "A",
    "9lives",
    "a--b",
    "-a",
    "a-",
    "a_b",
    "a/b",
    "../x",
    "a b",
    "a\n",
    "class",
    "import",
    "a" * (MAX_NAME_CHARS + 1),
]


@pytest.mark.parametrize("name", BAD_NAMES, ids=repr)
def test_a_bad_name_is_refused_before_anything_is_read(root: Path, name: str) -> None:
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, name)

    assert str(refused.value) == BAD_NAME
    assert snapshot(root) == before


def test_the_name_is_checked_before_the_tree_is_looked_at(tmp_path: Path) -> None:
    with pytest.raises(ScaffoldError) as refused:
        plan_workload(tmp_path, "../x")

    assert str(refused.value) == BAD_NAME


def test_a_name_of_forty_characters_is_accepted_and_one_of_forty_one_is_not(
    root: Path,
) -> None:
    plan = plan_workload(root, LONG_NAME)

    assert len(LONG_NAME) == MAX_NAME_CHARS
    assert plan.name == LONG_NAME
    assert plan.module == LONG_NAME.replace("-", "_")


def break_layout_without_pyproject(root: Path) -> None:
    (root / "pyproject.toml").unlink()


def break_layout_pyproject_is_not_toml(root: Path) -> None:
    (root / "pyproject.toml").write_text("[project\nname = \n", encoding="utf-8")


def break_layout_other_project(root: Path) -> None:
    edit(
        root / "pyproject.toml",
        lambda t: t.replace('name = "meridian"', 'name = "x"', 1),
    )


def break_layout_no_graphs_table(root: Path) -> None:
    edit(
        root / "pyproject.toml",
        lambda t: t.replace(f'[project.entry-points."{GRAPHS}"]', "[project.x]"),
    )


def break_layout_no_evaluations_table(root: Path) -> None:
    edit(
        root / "pyproject.toml",
        lambda t: t.replace(f'[project.entry-points."{EVALUATIONS}"]', "[project.x]"),
    )


def break_layout_no_agents_file(root: Path) -> None:
    (root / "config/registry/agents.yaml").unlink()


def break_layout_workloads_is_a_file(root: Path) -> None:
    workloads = root / "src/meridian/workloads"
    workloads.rmdir()
    workloads.write_text("", encoding="utf-8")


def break_layout_no_workloads(root: Path) -> None:
    (root / "src/meridian/workloads").rmdir()


LAYOUT_DEFECTS = [
    break_layout_without_pyproject,
    break_layout_pyproject_is_not_toml,
    break_layout_other_project,
    break_layout_no_graphs_table,
    break_layout_no_evaluations_table,
    break_layout_no_agents_file,
    break_layout_workloads_is_a_file,
    break_layout_no_workloads,
]


@pytest.mark.parametrize("defect", LAYOUT_DEFECTS, ids=lambda f: f.__name__)
def test_a_tree_that_is_not_a_meridian_checkout_is_refused(
    root: Path, defect: Callable[[Path], None]
) -> None:
    defect(root)
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == NOT_A_CHECKOUT
    assert snapshot(root) == before


def test_a_registry_that_does_not_validate_is_refused(root: Path) -> None:
    edit(root / "config/registry/tenants.yaml", lambda t: t + "\nbroken: [\n")
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == REGISTRY_INVALID
    assert snapshot(root) == before


def test_a_tree_defect_is_reported_before_a_registry_defect(root: Path) -> None:
    edit(root / "config/registry/tenants.yaml", lambda t: t + "\nbroken: [\n")
    break_layout_no_workloads(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == NOT_A_CHECKOUT


def test_a_registry_defect_is_reported_before_a_taken_name(root: Path) -> None:
    edit(root / "config/registry/tenants.yaml", lambda t: t + "\nbroken: [\n")

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, "claims-triage")

    assert str(refused.value) == REGISTRY_INVALID


def test_a_name_an_agent_already_has_is_refused(root: Path) -> None:
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, "claims-triage")

    assert str(refused.value) == NAME_TAKEN
    assert snapshot(root) == before


@pytest.mark.parametrize("group", [GRAPHS, EVALUATIONS])
def test_a_name_in_only_one_entry_point_table_is_refused(
    root: Path, group: str
) -> None:
    header = f'[project.entry-points."{group}"]\n'
    edit(
        root / "pyproject.toml",
        lambda t: t.replace(header, header + f'{NAME} = "x.y:z"\n'),
    )

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == NAME_TAKEN


def occupy_with_a_directory(path: Path) -> None:
    path.mkdir(parents=True)


def occupy_with_a_file(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("", encoding="utf-8")


def occupy_with_a_dangling_symlink(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.symlink_to(path.parent / "nowhere")


OCCUPIERS = [
    occupy_with_a_directory,
    occupy_with_a_file,
    occupy_with_a_dangling_symlink,
]
TAKEN_PATHS = [
    f"src/meridian/workloads/{MODULE}",
    f"tests/meridian/workloads/{MODULE}",
    f"data/evaluation/{NAME}",
]


@pytest.mark.parametrize("occupier", OCCUPIERS, ids=lambda f: f.__name__)
@pytest.mark.parametrize("taken", TAKEN_PATHS)
def test_a_path_the_workload_would_take_is_refused_whatever_is_there(
    root: Path, taken: str, occupier: Callable[[Path], None]
) -> None:
    occupier(root / taken)
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == NAME_TAKEN
    assert snapshot(root) == before


@pytest.mark.parametrize("name", ["yes", "no", "on", "off", "true", "false", "null"])
def test_a_word_yaml_reads_as_something_other_than_text_is_refused_first(
    tmp_path: Path, name: str
) -> None:
    # An empty directory: the name is refused before the tree is looked at.
    with pytest.raises(ScaffoldError) as refused:
        plan_workload(tmp_path, name)

    assert str(refused.value) == AMBIGUOUS_NAME


def test_a_name_yaml_reads_as_text_passes_the_ambiguity_check(root: Path) -> None:
    assert plan_workload(root, "yesterday").name == "yesterday"


def test_an_agents_file_in_flow_style_fails_the_agents_edit(root: Path) -> None:
    # The registry reads it, but lines appended in block style do not parse.
    path = root / "config/registry/agents.yaml"
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    path.write_text(json.dumps(document) + "\n", encoding="utf-8")
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == AGENTS_EDIT_UNVERIFIED
    assert snapshot(root) == before


def test_a_pyproject_table_the_text_edit_cannot_find_fails_the_pyproject_edit(
    root: Path,
) -> None:
    # The table exists for tomllib but not as a header line the edit can find.
    edit(
        root / "pyproject.toml",
        lambda t: t.replace(
            f'[project.entry-points."{GRAPHS}"]',
            f'[ project.entry-points."{GRAPHS}" ]',
        ),
    )

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == PYPROJECT_EDIT_UNVERIFIED


def nothing_to_arrange(root: Path) -> None:
    return None


def occupy_the_module_directory(root: Path) -> None:
    occupy_with_a_file(root / f"src/meridian/workloads/{MODULE}")


def break_the_registry(root: Path) -> None:
    edit(root / "config/registry/tenants.yaml", lambda t: t + "x: [")


@pytest.mark.parametrize(
    ("name", "arrange"),
    [
        pytest.param("9lives", nothing_to_arrange, id="pattern"),
        pytest.param("a" * (MAX_NAME_CHARS + 1), nothing_to_arrange, id="length"),
        pytest.param("../x", nothing_to_arrange, id="traversal"),
        pytest.param("class", nothing_to_arrange, id="keyword-class"),
        pytest.param("import", nothing_to_arrange, id="keyword-import"),
        pytest.param("claims-triage", nothing_to_arrange, id="agent-exists"),
        pytest.param(NAME, occupy_the_module_directory, id="directory-taken"),
        pytest.param(NAME, break_layout_no_agents_file, id="not-a-checkout"),
        pytest.param(NAME, break_the_registry, id="registry-invalid"),
        pytest.param("yes", nothing_to_arrange, id="yaml-boolean"),
    ],
)
def test_no_refusal_quotes_the_name(
    root: Path, name: str, arrange: Callable[[Path], None]
) -> None:
    arrange(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, name)

    assert name not in str(refused.value)
    assert name.replace("-", "_") not in str(refused.value)


def test_every_refusal_text_is_fixed_and_none_holds_a_format_field() -> None:
    texts = [
        BAD_NAME,
        AMBIGUOUS_NAME,
        NOT_A_CHECKOUT,
        REGISTRY_INVALID,
        NAME_TAKEN,
        AGENTS_EDIT_UNVERIFIED,
        PYPROJECT_EDIT_UNVERIFIED,
        PATH_EXISTS,
    ]
    assert len(set(texts)) == len(texts)
    assert all(text.strip() for text in texts)


def written(root: Path, name: str = NAME) -> Plan:
    plan = plan_workload(root, name)
    write_plan(root, plan)
    return plan


def test_write_plan_writes_the_files_and_the_two_edits(root: Path) -> None:
    plan = written(root)

    for relative, text in {**plan.created, **plan.changed}.items():
        assert (root / relative).read_bytes() == text.encode("utf-8")


def test_the_entry_points_are_added_and_every_old_key_is_unchanged(
    root: Path,
) -> None:
    old = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))

    written(root)

    new = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    expected = json.loads(json.dumps(old))
    expected["project"]["entry-points"][GRAPHS][NAME] = (
        f"meridian.workloads.{MODULE}.graph:build"
    )
    expected["project"]["entry-points"][EVALUATIONS][NAME] = (
        f"meridian.workloads.{MODULE}.evaluation:EVALUATION"
    )
    assert new == expected


def test_every_comment_of_the_two_edited_files_is_still_there_in_order(
    root: Path,
) -> None:
    old = {
        name: (root / name).read_text(encoding="utf-8")
        for name in ("pyproject.toml", "config/registry/agents.yaml")
    }

    written(root)

    for name, text in old.items():
        assert comment_lines(text)  # the test would prove nothing otherwise
        new = (root / name).read_text(encoding="utf-8")
        assert comment_lines(new) == comment_lines(text)


def test_the_registry_with_the_new_agent_validates_and_grants_it_nothing(
    root: Path,
) -> None:
    old_tenants = (root / "config/registry/tenants.yaml").read_bytes()
    others = {
        path.name: path.read_bytes()
        for path in (root / "config/registry").glob("*.yaml")
        if path.name != "agents.yaml"
    }

    written(root)

    registry = load_registry(root / "config/registry")
    agent = registry.agent(NAME)
    assert agent is not None
    assert agent.kind == "graph"
    assert agent.tools == ()
    assert all(NAME not in tenant.agents for tenant in registry.tenants)
    assert (root / "config/registry/tenants.yaml").read_bytes() == old_tenants
    assert {
        path.name: path.read_bytes()
        for path in (root / "config/registry").glob("*.yaml")
        if path.name != "agents.yaml"
    } == others


def test_the_old_agents_are_unchanged_after_the_write(root: Path) -> None:
    before = yaml.safe_load((root / "config/registry/agents.yaml").read_text("utf-8"))

    written(root)

    after = yaml.safe_load((root / "config/registry/agents.yaml").read_text("utf-8"))
    assert after["agents"][:-1] == before["agents"]
    assert after["agents"][-1] == {
        "id": NAME,
        "description": (
            f"The {NAME} workload, generated by `meridian workload new`; "
            "it calls no tool."
        ),
        "tools": [],
    }


def test_the_generated_golden_set_passes_the_platform_fingerprint(
    root: Path,
) -> None:
    written(root)

    golden_set = golden_set_of(root / f"data/evaluation/{NAME}/golden/manifest.json")

    assert tuple(golden_set.files) == ("cases.json",)
    assert golden_set.generator_version == "0"
    assert golden_set.seed == 0


def test_the_files_replaced_keep_their_mode(root: Path) -> None:
    for relative in ("pyproject.toml", "config/registry/agents.yaml"):
        (root / relative).chmod(0o640)

    written(root)

    for relative in ("pyproject.toml", "config/registry/agents.yaml"):
        assert stat.S_IMODE((root / relative).stat().st_mode) == 0o640


def test_write_plan_leaves_no_temporary_file_beside_the_edited_files(
    root: Path,
) -> None:
    written(root)

    assert not list(root.rglob("*.tmp"))


def test_write_plan_refuses_when_a_created_path_appeared_after_planning(
    root: Path,
) -> None:
    plan = plan_workload(root, NAME)
    occupy_with_a_dangling_symlink(root / f"data/evaluation/{NAME}/golden/cases.json")
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        write_plan(root, plan)

    assert str(refused.value) == PATH_EXISTS
    assert snapshot(root) == before


def fail_replace_on(monkeypatch: pytest.MonkeyPatch, target: str) -> None:
    real = os.replace

    def replace(source: Any, destination: Any, *args: Any, **kwargs: Any) -> None:
        if Path(destination).name == target:
            raise PermissionError(13, "denied", str(destination))
        real(source, destination, *args, **kwargs)

    monkeypatch.setattr(os, "replace", replace)


@pytest.mark.parametrize("target", ["pyproject.toml", "agents.yaml"])
def test_a_failed_replacement_leaves_the_tree_byte_identical(
    root: Path, monkeypatch: pytest.MonkeyPatch, target: str
) -> None:
    plan = plan_workload(root, NAME)
    before = snapshot(root)
    fail_replace_on(monkeypatch, target)

    with pytest.raises(ScaffoldError) as refused:
        write_plan(root, plan)

    assert str(refused.value) == WRITE_FAILED.format("PermissionError")
    assert "denied" not in str(refused.value)
    assert target not in str(refused.value)
    assert snapshot(root) == before


def test_a_rollback_removes_only_the_directories_the_call_made(
    root: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    (root / "data/evaluation/other/golden").mkdir(parents=True)
    (root / "tests/meridian/workloads/claims_triage").mkdir(parents=True)
    plan = plan_workload(root, NAME)
    before = snapshot(root)
    fail_replace_on(monkeypatch, "pyproject.toml")

    with pytest.raises(ScaffoldError):
        write_plan(root, plan)

    assert snapshot(root) == before


def test_a_failed_creation_is_rolled_back_too(
    root: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    plan = plan_workload(root, NAME)
    before = snapshot(root)
    real = Path.mkdir

    def mkdir(self: Path, *args: Any, **kwargs: Any) -> None:
        # After the package's and the test's directories exist.
        if self.name == "golden":
            raise OSError(28, "no space")
        real(self, *args, **kwargs)

    monkeypatch.setattr(Path, "mkdir", mkdir)

    with pytest.raises(ScaffoldError) as refused:
        write_plan(root, plan)

    assert str(refused.value) == WRITE_FAILED.format("OSError")
    assert snapshot(root) == before


def test_a_rollback_that_fails_says_so(
    root: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    plan = plan_workload(root, NAME)
    real = os.replace
    agents_replacements = []

    def replace(source: Any, destination: Any, *args: Any, **kwargs: Any) -> None:
        # The pyproject replacement fails, and so does restoring agents.yaml.
        if Path(destination).name == "agents.yaml":
            agents_replacements.append(source)
        if Path(destination).name == "pyproject.toml" or len(agents_replacements) > 1:
            raise PermissionError(13, "denied")
        real(source, destination, *args, **kwargs)

    monkeypatch.setattr(os, "replace", replace)

    with pytest.raises(ScaffoldError) as refused:
        write_plan(root, plan)

    assert str(refused.value) == ROLLBACK_FAILED.format("PermissionError")
    assert "denied" not in str(refused.value)


def test_running_the_scaffold_twice_is_refused_and_changes_nothing(
    root: Path,
) -> None:
    written(root)
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == NAME_TAKEN
    assert snapshot(root) == before


def rendered_python(plan: Plan) -> dict[str, str]:
    return {path: text for path, text in plan.created.items() if path.endswith(".py")}


@pytest.mark.parametrize("length", range(1, MAX_NAME_CHARS + 1))
def test_no_rendered_line_is_longer_than_88_characters(root: Path, length: int) -> None:
    half = length // 2
    name = "a" * length if length < 3 else "a" * half + "-" + "b" * (length - half - 1)

    plan = plan_workload(root, name)

    assert len(name) == length
    for path, text in plan.created.items():
        longest = max(len(line) for line in text.splitlines())
        assert longest <= 88, (path, longest)


@pytest.mark.parametrize("name", ["a", NAME, LONG_NAME])
def test_the_rendered_python_is_clean_under_ruff(root: Path, name: str) -> None:
    plan = plan_workload(root, name)
    write_plan(root, plan)
    ruff = str(Path(sys.executable).parent / "ruff")
    files = sorted(rendered_python(plan))

    for command in (["check"], ["format", "--check", "--diff"]):
        completed = subprocess.run(
            [ruff, *command, "--no-cache", *FIRST_PARTY, *files],
            cwd=root,
            capture_output=True,
            text=True,
            timeout=RUFF_TIMEOUT_SECONDS,
            check=False,
        )
        assert completed.returncode == 0, completed.stdout + completed.stderr
    assert len(files) == 4


def test_a_template_substitutes_only_the_name_and_the_module(root: Path) -> None:
    plan = plan_workload(root, NAME)

    for path, text in plan.created.items():
        assert "$" not in text, path
        assert "{{" not in text, path


def test_the_scaffold_module_imports_no_agent_framework() -> None:
    source = Path(scaffold.__file__).read_text(encoding="utf-8")

    for forbidden in (
        "langgraph",
        "langchain",
        "meridian.runtime",
        "meridian.workloads",
    ):
        assert f"import {forbidden}" not in source
        assert f"from {forbidden}" not in source


def test_the_plan_is_immutable(root: Path) -> None:
    plan = plan_workload(root, NAME)

    with pytest.raises(AttributeError):
        plan.name = "other"  # type: ignore[misc]


def test_changed_and_created_are_mappings(root: Path) -> None:
    plan = plan_workload(root, NAME)

    assert isinstance(plan.created, Mapping)
    assert isinstance(plan.changed, Mapping)
