"""The workload scaffold's planning and refusals (S039, T-81).

Every test builds a small tree in ``tmp_path``: a copy of this repository's
``pyproject.toml`` and registry and an empty workloads directory. Nothing here
touches the real checkout.
"""

import errno
import json
import os
import shutil
import tomllib
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pytest
import yaml

from meridian.platform.cli import scaffold
from meridian.platform.cli.scaffold import (
    AGENTS_EDIT_UNVERIFIED,
    AGENTS_LIST_UNUSABLE,
    AMBIGUOUS_NAME,
    BAD_NAME,
    MAX_NAME_CHARS,
    NAME_TAKEN,
    NOT_A_CHECKOUT,
    PATH_EXISTS,
    PATH_OUTSIDE,
    PYPROJECT_EDIT_UNVERIFIED,
    PYPROJECT_HEADER_UNUSABLE,
    PYPROJECT_NOT_TOML,
    REGISTRY_COPY_FAILED,
    REGISTRY_EDIT_INVALID,
    REGISTRY_INVALID,
    REGISTRY_UNREADABLE,
    ROLLBACK_FAILED,
    STALE_PLAN,
    WRITE_FAILED,
    ScaffoldError,
    ScaffoldWriteError,
    plan_workload,
)
from meridian.platform.registry.loader import RegistryError, load_registry

NAME = "fraud-review"
MODULE = "fraud_review"
GRAPHS = "meridian.graphs"
EVALUATIONS = "meridian.evaluations"
LONG_NAME = "a" * 20 + "-" + "b" * 19
RUFF_TIMEOUT_SECONDS = 60
REPO = Path(__file__).resolve().parents[3]
LEAKED = "a-path-or-a-name-the-error-must-not-repeat"
# The small tree has no ``meridian.platform`` for ruff's import sorter to find, so
# it is told what the real checkout's layout shows it: ``meridian`` is ours.
FIRST_PARTY = ("--config", 'lint.isort.known-first-party = ["meridian"]')


def created_paths(module: str = MODULE, name: str = NAME) -> set[str]:
    return {
        f"src/meridian/workloads/{module}/__init__.py",
        f"src/meridian/workloads/{module}/graph.py",
        f"src/meridian/workloads/{module}/evaluation.py",
        f"tests/meridian/workloads/{module}/test_{module}_scaffold.py",
        f"data/evaluation/{name}/golden/cases.json",
        f"data/evaluation/{name}/golden/manifest.json",
    }


def snapshot(root: Path) -> dict[str, object]:
    """Every path under ``root``: a file's bytes, a symlink's target, a
    directory as ``None``, so that a stray directory or temp file shows."""
    found: dict[str, object] = {}
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root).as_posix()
        if path.is_symlink():
            found[relative] = ("link", os.readlink(path))
        elif path.is_dir():
            found[relative] = None
        else:
            found[relative] = path.read_bytes()
    return found


def edit(path: Path, change: Callable[[str], str]) -> None:
    text = path.read_bytes().decode("utf-8")
    path.write_bytes(change(text).encode("utf-8"))


def comment_lines(text: str) -> list[str]:
    return [line.strip() for line in text.splitlines() if line.lstrip()[:1] == "#"]


def test_a_plan_creates_six_files_and_changes_two_and_writes_nothing(
    root: Path,
) -> None:
    before = snapshot(root)

    plan = plan_workload(root, NAME)

    assert plan.name == NAME
    assert plan.module == MODULE
    assert set(plan.created) == created_paths()
    assert len(plan.created) == 6
    assert set(plan.changed) == {"config/registry/agents.yaml", "pyproject.toml"}
    assert snapshot(root) == before


def test_the_new_agent_is_appended_to_agents_yaml_as_three_lines(root: Path) -> None:
    old = (root / "config/registry/agents.yaml").read_text(encoding="utf-8")

    plan = plan_workload(root, NAME)

    new = plan.changed["config/registry/agents.yaml"]
    assert new == (
        old
        + f"  - id: {NAME}\n"
        + f"    description: The {NAME} workload, generated by "
        + "`meridian workload new`; it calls no tool.\n"
        + "    tools: []\n"
    )


def test_a_file_with_crlf_line_endings_gets_the_agent_in_crlf(root: Path) -> None:
    path = root / "config/registry/agents.yaml"
    path.write_bytes(path.read_bytes().replace(b"\r\n", b"\n").replace(b"\n", b"\r\n"))
    old = path.read_bytes().decode("utf-8")

    plan = plan_workload(root, NAME)

    assert plan.changed["config/registry/agents.yaml"] == (
        old
        + f"  - id: {NAME}\r\n"
        + f"    description: The {NAME} workload, generated by "
        + "`meridian workload new`; it calls no tool.\r\n"
        + "    tools: []\r\n"
    )


def test_a_file_without_a_final_newline_gets_one_before_the_agent(root: Path) -> None:
    path = root / "config/registry/agents.yaml"
    edit(path, str.rstrip)

    plan = plan_workload(root, NAME)

    new = plan.changed["config/registry/agents.yaml"]
    assert new.startswith(path.read_text(encoding="utf-8") + f"\n  - id: {NAME}\n")


def test_each_entry_point_follows_its_tables_last_key_line(root: Path) -> None:
    old = (root / "pyproject.toml").read_text(encoding="utf-8")

    plan = plan_workload(root, NAME)

    new = plan.changed["pyproject.toml"]
    # The last key of each table as the file has it today, whatever workloads it
    # lists: a tree with a second workload must not fail this test.
    tables = tomllib.loads(old)["project"]["entry-points"]
    last_graph, graph_value = list(tables[GRAPHS].items())[-1]
    last_evaluation, evaluation_value = list(tables[EVALUATIONS].items())[-1]
    graph_old = f'{last_graph} = "{graph_value}"\n'
    graph_new = f'{NAME} = "meridian.workloads.{MODULE}.graph:build"\n'
    evaluation_old = f'{last_evaluation} = "{evaluation_value}"\n'
    evaluation_new = f'{NAME} = "meridian.workloads.{MODULE}.evaluation:EVALUATION"\n'
    assert old.count(graph_old) == 1 and old.count(evaluation_old) == 1
    assert new == old.replace(graph_old, graph_old + graph_new).replace(
        evaluation_old, evaluation_old + evaluation_new
    )
    # The blank line and the comment that followed the graphs table stay after
    # the inserted key.
    assert graph_new + "\n# `meridian eval run`" in new


MINIMAL_PYPROJECT = (
    '[project]\nname = "meridian"\n\n'
    '[project.entry-points."meridian.graphs"]\nclaims-triage = "a.b:c"\n\n'
    "# a comment that belongs to the next table\n"
    '[project.entry-points."meridian.evaluations"]\nclaims-triage = "d.e:f"'
)


@pytest.mark.parametrize("line_ending", ["\n", "\r\n"], ids=["lf", "crlf"])
def test_the_line_endings_and_a_missing_final_newline_are_kept(
    root: Path, line_ending: str
) -> None:
    text = MINIMAL_PYPROJECT.replace("\n", line_ending)
    (root / "pyproject.toml").write_bytes(text.encode("utf-8"))
    graph_old = 'claims-triage = "a.b:c"'
    graph_new = f'{NAME} = "meridian.workloads.{MODULE}.graph:build"'
    evaluation_old = 'claims-triage = "d.e:f"'
    evaluation_new = f'{NAME} = "meridian.workloads.{MODULE}.evaluation:EVALUATION"'

    plan = plan_workload(root, NAME)

    # The inserted line takes the file's line ending, and the last line, which
    # had none, still has none.
    assert plan.changed["pyproject.toml"] == text.replace(
        graph_old, graph_old + line_ending + graph_new, 1
    ).replace(evaluation_old, evaluation_old + line_ending + evaluation_new, 1)


# Names the pattern, the length limit or the module check refuse.
BAD_NAMES = [
    "",
    "A",
    "9lives",
    "a--b",
    "-a",
    "a-",
    "a_b",
    "a/b",
    "../x",
    "a b",
    "a\n",
    "class",
    "import",
    "a" * (MAX_NAME_CHARS + 1),
]


@pytest.mark.parametrize("name", BAD_NAMES, ids=repr)
def test_a_bad_name_is_refused_before_anything_is_read(root: Path, name: str) -> None:
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, name)

    assert str(refused.value) == BAD_NAME
    assert snapshot(root) == before


def test_the_name_is_checked_before_the_tree_is_looked_at(tmp_path: Path) -> None:
    with pytest.raises(ScaffoldError) as refused:
        plan_workload(tmp_path, "../x")

    assert str(refused.value) == BAD_NAME


def test_a_name_of_forty_characters_is_accepted_and_one_of_forty_one_is_not(
    root: Path,
) -> None:
    plan = plan_workload(root, LONG_NAME)

    assert len(LONG_NAME) == MAX_NAME_CHARS
    assert plan.name == LONG_NAME
    assert plan.module == LONG_NAME.replace("-", "_")


def break_layout_without_pyproject(root: Path) -> None:
    (root / "pyproject.toml").unlink()


def break_layout_other_project(root: Path) -> None:
    edit(
        root / "pyproject.toml",
        lambda t: t.replace('name = "meridian"', 'name = "x"', 1),
    )


def break_layout_no_graphs_table(root: Path) -> None:
    edit(
        root / "pyproject.toml",
        lambda t: t.replace(f'[project.entry-points."{GRAPHS}"]', "[project.x]"),
    )


def break_layout_no_evaluations_table(root: Path) -> None:
    edit(
        root / "pyproject.toml",
        lambda t: t.replace(f'[project.entry-points."{EVALUATIONS}"]', "[project.x]"),
    )


def break_layout_no_agents_file(root: Path) -> None:
    (root / "config/registry/agents.yaml").unlink()


def break_layout_workloads_is_a_file(root: Path) -> None:
    workloads = root / "src/meridian/workloads"
    workloads.rmdir()
    workloads.write_text("", encoding="utf-8")


def break_layout_no_workloads(root: Path) -> None:
    (root / "src/meridian/workloads").rmdir()


LAYOUT_DEFECTS = [
    break_layout_without_pyproject,
    break_layout_other_project,
    break_layout_no_graphs_table,
    break_layout_no_evaluations_table,
    break_layout_no_agents_file,
    break_layout_workloads_is_a_file,
    break_layout_no_workloads,
]


@pytest.mark.parametrize("defect", LAYOUT_DEFECTS, ids=lambda f: f.__name__)
def test_a_tree_that_is_not_a_meridian_checkout_is_refused(
    root: Path, defect: Callable[[Path], None]
) -> None:
    defect(root)
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == NOT_A_CHECKOUT
    assert snapshot(root) == before


@pytest.mark.parametrize(
    "content",
    [b"[project\nname = \n", b"\xff\xfe"],
    ids=["not-toml", "not-utf-8"],
)
def test_a_pyproject_that_cannot_be_read_as_toml_says_so(
    root: Path, content: bytes
) -> None:
    (root / "pyproject.toml").write_bytes(content)
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == PYPROJECT_NOT_TOML
    assert snapshot(root) == before


def test_a_refusal_for_a_tree_that_is_no_checkout_says_what_to_do(
    root: Path,
) -> None:
    (root / "pyproject.toml").unlink()

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value).endswith(
        ": run the command at the checkout's root or pass --root"
    )


def test_a_registry_that_does_not_validate_is_refused_with_the_registrys_messages(
    root: Path,
) -> None:
    edit(root / "config/registry/tenants.yaml", lambda t: t + "\nbroken: [\n")
    before = snapshot(root)
    with pytest.raises(RegistryError) as raised:
        load_registry(root / "config/registry")

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == REGISTRY_INVALID
    assert "meridian registry validate --registry-dir" in REGISTRY_INVALID
    assert raised.value.errors  # the test would prove nothing otherwise
    assert refused.value.details == tuple(
        f"the registry: {message}" for message in raised.value.errors
    )
    assert snapshot(root) == before


def test_a_registry_that_cannot_be_read_is_refused_not_a_traceback(
    root: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    def unreadable(directory: Path) -> None:
        raise PermissionError(errno.EACCES, LEAKED, str(directory))

    monkeypatch.setattr(scaffold, "load_registry", unreadable)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == REGISTRY_UNREADABLE.format("PermissionError")
    assert LEAKED not in str(refused.value)
    assert not isinstance(refused.value, ScaffoldWriteError)


def test_a_tree_defect_is_reported_before_a_registry_defect(root: Path) -> None:
    edit(root / "config/registry/tenants.yaml", lambda t: t + "\nbroken: [\n")
    break_layout_no_workloads(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == NOT_A_CHECKOUT


def test_a_registry_defect_is_reported_before_a_taken_name(root: Path) -> None:
    edit(root / "config/registry/tenants.yaml", lambda t: t + "\nbroken: [\n")

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, "claims-triage")

    assert str(refused.value) == REGISTRY_INVALID


def test_a_name_an_agent_already_has_is_refused(root: Path) -> None:
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, "claims-triage")

    assert str(refused.value).startswith(NAME_TAKEN.format(""))
    assert snapshot(root) == before


def test_a_name_only_an_agent_has_is_refused_with_no_entry_point_or_directory(
    root: Path,
) -> None:
    agent = "knowledge-ingestion"
    registry = load_registry(root / "config/registry")
    assert registry.agent(agent) is not None
    assert agent not in (root / "pyproject.toml").read_text(encoding="utf-8")
    assert not (root / f"src/meridian/workloads/{agent.replace('-', '_')}").exists()

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, agent)

    assert str(refused.value).startswith(NAME_TAKEN.format(""))


@pytest.mark.parametrize("group", [GRAPHS, EVALUATIONS])
def test_a_name_in_only_one_entry_point_table_is_refused(
    root: Path, group: str
) -> None:
    header = f'[project.entry-points."{group}"]\n'
    edit(
        root / "pyproject.toml",
        lambda t: t.replace(header, header + f'{NAME} = "x.y:z"\n'),
    )

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value).startswith(NAME_TAKEN.format(""))


def occupy_with_a_directory(path: Path) -> None:
    path.mkdir(parents=True)


def occupy_with_a_file(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("", encoding="utf-8")


def occupy_with_a_dangling_symlink(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.symlink_to(path.parent / "nowhere")


OCCUPIERS = [
    occupy_with_a_directory,
    occupy_with_a_file,
    occupy_with_a_dangling_symlink,
]
TAKEN_PATHS = [
    f"src/meridian/workloads/{MODULE}",
    f"src/meridian/workloads/{MODULE}.py",
    f"tests/meridian/workloads/{MODULE}",
    f"data/evaluation/{NAME}",
]


@pytest.mark.parametrize("occupier", OCCUPIERS, ids=lambda f: f.__name__)
@pytest.mark.parametrize("taken", TAKEN_PATHS)
def test_a_path_the_workload_would_take_is_refused_whatever_is_there(
    root: Path, taken: str, occupier: Callable[[Path], None]
) -> None:
    occupier(root / taken)
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value).startswith(NAME_TAKEN.format(""))
    assert snapshot(root) == before


def leave_the_root_at(root: Path, relative: str, outside: Path) -> None:
    """Make ``relative`` a symbolic link to the directory ``outside`` the root."""
    path = root / relative
    if path.is_dir():
        shutil.rmtree(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.symlink_to(outside, target_is_directory=True)


@pytest.mark.parametrize(
    "relative",
    [
        "src/meridian/workloads",
        "config/registry",
        "data/evaluation",
        "data",
        "tests/meridian/workloads",
        "tests/meridian",
        "tests",
    ],
)
def test_a_directory_the_workload_is_written_to_that_leaves_the_checkout_is_refused(
    root: Path, tmp_path_factory: pytest.TempPathFactory, relative: str
) -> None:
    outside = tmp_path_factory.mktemp("outside")
    (outside / "agents.yaml").write_bytes(
        (root / "config/registry/agents.yaml").read_bytes()
    )
    leave_the_root_at(root, relative, outside)
    if relative == "config/registry":  # the registry is read through the link
        shutil.copytree(REPO / "config/registry", outside, dirs_exist_ok=True)
    before = snapshot(root)
    outside_before = snapshot(outside)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == PATH_OUTSIDE
    assert snapshot(root) == before
    assert snapshot(outside) == outside_before


@pytest.mark.parametrize("relative", ["pyproject.toml", "config/registry/agents.yaml"])
def test_an_edited_file_that_is_a_symbolic_link_is_refused(
    root: Path, tmp_path_factory: pytest.TempPathFactory, relative: str
) -> None:
    outside = tmp_path_factory.mktemp("outside")
    moved = outside / "moved"
    shutil.move(root / relative, moved)
    (root / relative).symlink_to(moved)
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == PATH_OUTSIDE
    assert snapshot(root) == before
    assert snapshot(outside) == {"moved": moved.read_bytes()}


def test_a_link_that_stays_inside_the_checkout_is_not_refused(root: Path) -> None:
    (root / "data").mkdir()
    (root / "elsewhere").mkdir()
    (root / "data/evaluation").symlink_to(root / "elsewhere", target_is_directory=True)

    assert plan_workload(root, NAME).name == NAME


@pytest.mark.parametrize("name", ["yes", "no", "on", "off", "true", "false", "null"])
def test_a_word_yaml_reads_as_something_other_than_text_is_refused_first(
    tmp_path: Path, name: str
) -> None:
    # An empty directory: the name is refused before the tree is looked at.
    with pytest.raises(ScaffoldError) as refused:
        plan_workload(tmp_path, name)

    assert str(refused.value) == AMBIGUOUS_NAME


def test_a_name_yaml_reads_as_text_passes_the_ambiguity_check(root: Path) -> None:
    assert plan_workload(root, "yesterday").name == "yesterday"


def flow_style_agents(root: Path) -> None:
    # The registry reads it, but lines appended in block style do not parse.
    path = root / "config/registry/agents.yaml"
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    path.write_text(json.dumps(document) + "\n", encoding="utf-8")


def test_an_agents_file_in_flow_style_fails_the_agents_edit(root: Path) -> None:
    flow_style_agents(root)
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    # The whole file is one line of JSON: the list starts on line 1.
    assert str(refused.value) == AGENTS_LIST_UNUSABLE.format(1)
    assert "block style" in AGENTS_LIST_UNUSABLE
    assert "`agents` last" in AGENTS_LIST_UNUSABLE
    assert snapshot(root) == before


def test_the_parse_step_alone_refuses_an_edit_the_registry_check_would_accept(
    root: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    flow_style_agents(root)
    monkeypatch.setattr(scaffold, "_registry_with", lambda directory, text: None)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == AGENTS_LIST_UNUSABLE.format(1)


def test_the_registry_check_alone_refuses_an_edit_the_parse_step_accepts(
    root: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    def invalid(directory: Path, text: str) -> None:
        raise RegistryError(["agents.yaml: agents.9: a message of the registry's own"])

    monkeypatch.setattr(scaffold, "_registry_with", invalid)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == REGISTRY_EDIT_INVALID
    assert refused.value.details == (
        "the registry: agents.yaml: agents.9: a message of the registry's own",
    )


def test_a_registry_that_cannot_be_copied_to_check_the_edit_is_refused(
    root: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    def refuse(*args: Any, **kwargs: Any) -> None:
        raise PermissionError(errno.EACCES, LEAKED)

    monkeypatch.setattr(scaffold.shutil, "copytree", refuse)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == REGISTRY_COPY_FAILED.format("PermissionError")
    assert LEAKED not in str(refused.value)


def test_a_pyproject_table_the_text_edit_cannot_find_fails_the_pyproject_edit(
    root: Path,
) -> None:
    # The table exists for tomllib but not as a header line the edit can find.
    edit(
        root / "pyproject.toml",
        lambda t: t.replace(
            f'[project.entry-points."{GRAPHS}"]',
            f'[ project.entry-points."{GRAPHS}" ]',
        ),
    )

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == PYPROJECT_EDIT_UNVERIFIED


TOML_WITH_A_HEADER_IN_A_STRING = (
    '[project]\nname = "meridian"\ndescription = """\n'
    '[project.entry-points."meridian.graphs"]\n"""\n\n'
    '[ project.entry-points."meridian.graphs" ]\nclaims-triage = "a.b:c"\n\n'
    '[project.entry-points."meridian.evaluations"]\nclaims-triage = "d.e:f"\n'
)
# The first header is the real one, so an edit that took it would be right: only
# the refusal of a header seen twice stops this one.
TOML_WITH_A_HEADER_TWICE = (
    '[project]\nname = "meridian"\n\n'
    '[project.entry-points."meridian.graphs"]\nclaims-triage = "a.b:c"\n\n'
    '[project.entry-points."meridian.evaluations"]\nclaims-triage = "d.e:f"\n\n'
    '[tool.x]\nnote = """\n[project.entry-points."meridian.graphs"]\n"""\n'
)


@pytest.mark.parametrize(
    ("text", "message"),
    [
        (TOML_WITH_A_HEADER_IN_A_STRING, PYPROJECT_EDIT_UNVERIFIED),
        (
            TOML_WITH_A_HEADER_TWICE,
            # The header is on lines 4 and 12 of the text.
            PYPROJECT_HEADER_UNUSABLE.format(
                '[project.entry-points."meridian.graphs"]', "4 and 12"
            ),
        ),
    ],
    ids=["insertion-lands-in-the-string", "header-seen-twice"],
)
def test_a_header_line_inside_a_string_fails_the_pyproject_edit(
    root: Path, text: str, message: str
) -> None:
    (root / "pyproject.toml").write_text(text, encoding="utf-8")
    before = snapshot(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, NAME)

    assert str(refused.value) == message
    assert snapshot(root) == before


def test_the_trees_with_a_header_line_in_a_string_are_valid_toml() -> None:
    for text in (TOML_WITH_A_HEADER_IN_A_STRING, TOML_WITH_A_HEADER_TWICE):
        document = tomllib.loads(text)
        assert document["project"]["entry-points"][GRAPHS] == {"claims-triage": "a.b:c"}


def nothing_to_arrange(root: Path) -> None:
    return None


def occupy_the_module_directory(root: Path) -> None:
    occupy_with_a_file(root / f"src/meridian/workloads/{MODULE}")


def publish_the_name_in_the_graphs_group(root: Path) -> None:
    header = f'[project.entry-points."{GRAPHS}"]\n'
    edit(
        root / "pyproject.toml",
        lambda t: t.replace(header, header + f'{NAME} = "x.y:z"\n'),
    )


def comment_on_the_graphs_header(root: Path) -> None:
    header = f'[project.entry-points."{GRAPHS}"]'
    edit(root / "pyproject.toml", lambda t: t.replace(header, header + "  # note"))


def break_pyproject_toml(root: Path) -> None:
    (root / "pyproject.toml").write_text("[project\nname = \n", encoding="utf-8")


def break_the_registry(root: Path) -> None:
    edit(root / "config/registry/tenants.yaml", lambda t: t + "x: [")


@pytest.mark.parametrize(
    ("name", "arrange"),
    [
        pytest.param("9lives", nothing_to_arrange, id="pattern"),
        pytest.param("a" * (MAX_NAME_CHARS + 1), nothing_to_arrange, id="length"),
        pytest.param("../x", nothing_to_arrange, id="traversal"),
        pytest.param("class", nothing_to_arrange, id="keyword-class"),
        pytest.param("import", nothing_to_arrange, id="keyword-import"),
        pytest.param("claims-triage", nothing_to_arrange, id="agent-exists"),
        pytest.param(NAME, occupy_the_module_directory, id="directory-taken"),
        pytest.param(
            NAME, publish_the_name_in_the_graphs_group, id="entry-point-taken"
        ),
        pytest.param(NAME, comment_on_the_graphs_header, id="header-with-a-comment"),
        pytest.param(NAME, break_layout_no_agents_file, id="not-a-checkout"),
        pytest.param(NAME, break_the_registry, id="registry-invalid"),
        pytest.param(NAME, break_pyproject_toml, id="pyproject-not-toml"),
        pytest.param(NAME, break_layout_no_workloads, id="not-a-checkout-no-dir"),
        pytest.param(NAME, flow_style_agents, id="agents-edit-shape"),
        pytest.param("yes", nothing_to_arrange, id="yaml-boolean"),
    ],
)
def test_no_refusal_quotes_the_name(
    root: Path, name: str, arrange: Callable[[Path], None]
) -> None:
    arrange(root)

    with pytest.raises(ScaffoldError) as refused:
        plan_workload(root, name)

    assert name not in str(refused.value)
    assert name.replace("-", "_") not in str(refused.value)


def test_every_refusal_text_is_fixed_and_only_those_that_take_a_type_hold_a_field() -> (
    None
):
    texts = [
        BAD_NAME,
        AMBIGUOUS_NAME,
        NOT_A_CHECKOUT,
        REGISTRY_INVALID,
        NAME_TAKEN,
        AGENTS_EDIT_UNVERIFIED,
        AGENTS_LIST_UNUSABLE,
        PYPROJECT_EDIT_UNVERIFIED,
        PYPROJECT_HEADER_UNUSABLE,
        PYPROJECT_NOT_TOML,
        PATH_EXISTS,
        STALE_PLAN,
        REGISTRY_UNREADABLE,
        REGISTRY_EDIT_INVALID,
        REGISTRY_COPY_FAILED,
        WRITE_FAILED,
        ROLLBACK_FAILED,
    ]
    # The first four take the type of an error; the last three take what the
    # refusal says of the person's own tree: what holds a name, a line, a header.
    taking_a_type = {
        REGISTRY_UNREADABLE,
        REGISTRY_COPY_FAILED,
        WRITE_FAILED,
        ROLLBACK_FAILED,
        NAME_TAKEN,
        AGENTS_LIST_UNUSABLE,
        PYPROJECT_HEADER_UNUSABLE,
    }
    assert len(set(texts)) == len(texts)
    assert all(text.strip() for text in texts)
    assert {text for text in texts if "{}" in text} == taking_a_type
    assert all("{" not in text for text in texts if text not in taking_a_type)


def test_the_plan_is_immutable(root: Path) -> None:
    plan = plan_workload(root, NAME)

    with pytest.raises(AttributeError):
        plan.name = "other"  # type: ignore[misc]
    with pytest.raises(TypeError):
        plan.created["x"] = "y"  # type: ignore[index]
    with pytest.raises(TypeError):
        plan.changed["x"] = "y"  # type: ignore[index]
    with pytest.raises(TypeError):
        plan.base["x"] = "y"  # type: ignore[index]
